export const products = [
  {
    title: "Autonomous Agent Framework",
    description: "A minimal, composable framework for building agentic workflows. Built for developers who want to bypass heavy abstractions and write pure deterministic logic.",
    status: "Beta",
    link: "#",
  },
  {
    title: "AI Code Auditor",
    description: "Real-time security analysis for large codebases. Integrates directly into your CI/CD pipeline to catch vulnerabilities before they reach production.",
    status: "Early Access",
    link: "#",
  },
  {
    title: "Multi-Agent Playground",
    description: "A sandbox environment for testing complex interactions and negotiations between multiple autonomous models in an isolated arena.",
    status: "Internal Testing",
    link: "#",
  },
  {
    title: "Crumble DB",
    description: "An experimental vector database optimized for storing fragmented embeddings generated by continuously learning agents.",
    status: "Research Phase",
    link: "#",
  }
];
